"""
CatalogMind — Layer 11: Prompt Builder.

Pure string-building for the two LLM-assisted actions: RECOMMEND and
COMPARE. CLARIFY and REFUSE never reach this module — those are fully
deterministic (see decision.py / guardrails.py).

Design decisions:
  - No I/O, no network calls here — just string assembly. This makes
    prompt logic independently unit-testable without hitting Groq.
  - The LLM is given ONLY name + test_type (+ description if present)
    for each candidate — never the URL. URLs are attached to the final
    JSON response directly from Recommendation/ComparisonResult objects,
    never generated by the model. This is the core anti-hallucination
    guarantee: even if the LLM invents a URL in free text, the backend
    schema field is populated from ground truth, not LLM output.
  - System prompt explicitly forbids inventing assessment names.
  - Prompts are kept short (few hundred tokens) to respect the
    evaluator's latency budget and Groq's response speed.
"""

from schemas.chat_schema import Recommendation


_RECOMMEND_SYSTEM_PROMPT = (
    "You are CatalogMind, an assistant that recommends SHL assessments. "
    "You will be given a shortlist of assessments already selected by "
    "a backend retrieval system — these are the ONLY assessments you "
    "may mention. Do not invent, rename, or add any other assessment "
    "names. Do not mention or invent URLs — those are handled "
    "separately. Write a short, natural, helpful reply (2-4 sentences) "
    "introducing the shortlist and briefly explaining why it fits the "
    "user's request. Do not repeat the full list verbatim; the "
    "structured list is shown separately to the user."
)

_COMPARE_SYSTEM_PROMPT = (
    "You are CatalogMind, an assistant that compares SHL assessments. "
    "You will be given metadata for exactly two assessments from the "
    "official SHL catalog. Using ONLY the facts provided, write a "
    "short, natural comparison (3-5 sentences) highlighting their key "
    "differences (test type, dimensions measured, etc.). Do not invent "
    "any facts not present in the given metadata. Do not mention URLs."
)


def build_recommend_prompt(
    ctx,
    recommendations: list[Recommendation],
) -> tuple[str, str]:
    """
    Build (system_prompt, user_prompt) for the RECOMMEND action.

    Args:
        ctx:             ConversationContext (for role/seniority framing).
        recommendations: Already-ranked shortlist from recommender.py.

    Returns:
        (system_prompt, user_prompt) ready for call_groq().
    """
    lines = []
    for i, rec in enumerate(recommendations, start=1):
        lines.append(f"{i}. {rec.name} (type: {rec.test_type})")
    catalog_block = "\n".join(lines)

    role_line = f"Role: {ctx.role or 'not specified'}"
    seniority_line = f"Seniority: {ctx.seniority or 'not specified'}"

    user_prompt = (
        f"User request context:\n{role_line}\n{seniority_line}\n\n"
        f"Shortlisted assessments (backend-selected, do not alter):\n"
        f"{catalog_block}\n\n"
        f"Write a short reply introducing this shortlist to the user."
    )

    return _RECOMMEND_SYSTEM_PROMPT, user_prompt


def build_compare_prompt(comparison) -> tuple[str, str]:
    """
    Build (system_prompt, user_prompt) for the COMPARE action.

    Args:
        comparison: ComparisonResult from comparator.py (found=True).

    Returns:
        (system_prompt, user_prompt) ready for call_groq().
    """
    data = comparison.to_prompt_dict()

    lines = [
        f"Assessment A: {data['assessment_a']['name']}",
        f"Assessment B: {data['assessment_b']['name']}",
        "",
        "Comparison by dimension:",
    ]
    for row in data["comparison"]:
        same_note = "(same)" if row["same"] else "(differs)"
        lines.append(
            f"- {row['dimension']} {same_note}: "
            f"A = {row['a']} | B = {row['b']}"
        )

    user_prompt = (
        "\n".join(lines)
        + "\n\nWrite a short comparison between these two assessments, "
          "highlighting the dimensions that differ most."
    )

    return _COMPARE_SYSTEM_PROMPT, user_prompt